### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by ozett** [teemuhirsikangas/node-hikvision-omxplayer#1]
interesting idea and code,
maybe helpul a simple install manual on the readme?

👍 thx,
tozett

**Comment by ozett** [comment]
i tried this:
```
npm install --save teemuhirsikangas/node-hikvision-omxplayer#master
```
and got errors:

```
 ^
binding.target.mk:101: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/pi/node_modules/net-keepalive/node_modules/ref/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.37-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_modules/net-keepalive/node_modules/ref
gyp ERR! node -v v10.20.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN notsup Unsupported engine for net-keepalive@0.3.8: wanted: {"node":">=0.10 <=0.12||>=4 <=7"} (current: {"node":"10.20.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: net-keepalive@0.3.8
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-11T09_22_32_142Z-debug.log
```

as user "pi" with this versions:
```
pi@eg-buero-olaf:~ $ npm -v && node -v
6.14.4
v10.20.0
pi@eg-buero-olaf:~ $
```

any suggestions to fix this?

**Comment by ozett** [comment]
i was in the home-dir of the user, than i changed into the ".npm" dir 
and did the install again 
```
npm install --save teemuhirsikangas/node-hikvision-omxplayer#master
```

with this result

```
pi@eg-buero-olaf:~ $ cd .npm
pi@eg-buero-olaf:~/.npm $ npm install --save teemuhirsikangas/node-hikvision-omxplayer#master
npm WARN saveError ENOENT: no such file or directory, open '/home/pi/.npm/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/.npm/package.json'
npm WARN .npm No description
npm WARN .npm No repository field.
npm WARN .npm No README data
npm WARN .npm No license field.

+ hikvision-omxplayer@1.0.1
updated 1 package and audited 727 packages in 14.403s
found 15 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
pi@eg-buero-olaf:~/.npm $
```

**Comment by ozett** [comment]
_wrong_ directory again, so i went into `/home/pi/.node-red` and did first:
```
pi@eg-buero-olaf:~/.node-red $ npm install --save net-keepalive
```
and did secondly:
```
npm install --save teemuhirsikangas/node-hikvision-omxplayer
```

and  got errors:
```
In file included from ../../nan/nan.h:190:0,
                 from ../src/binding.cc:7:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:89:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
binding.target.mk:101: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/node-hikvision-api/node_modules/net-keepalive/node_modules/ref/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.37-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/node-hikvision-api/node_modules/net-keepalive/node_modules/ref
gyp ERR! node -v v10.20.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN notsup Unsupported engine for net-keepalive@0.3.8: wanted: {"node":">=0.10 <=0.12||>=4 <=7"} (current: {"node":"10.20.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: net-keepalive@0.3.8
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nyc@11.9.0 (node_modules/net-keepalive/node_modules/nyc):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Verification failed while extracting nyc@11.9.0:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Verification failed while extracting nyc@11.9.0:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha512-w8OdJAhXL5izerzZMdqzYKMj/pgHJyY3qEPYBjLLxrhcVoHEY9pU5ENIiZyCgG9OR7x3VcUMoD40o6PtVpfR4g== integrity checksum failed when using sha512: wanted sha512-w8OdJAhXL5izerzZMdqzYKMj/pgHJyY3qEPYBjLLxrhcVoHEY9pU5ENIiZyCgG9OR7x3VcUMoD40o6PtVpfR4g== but got sha512-spik45h9Nvztb4z/8pj+GWj64HAp7UVdGDyTRdbBzi9PGwQno69V/BXnmg0pGIc6RMFcGmX6b3z9MQhJ+YGfXg==. (2468111 bytes)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-11T09_58_30_096Z-debug.log
```

any suggestions?

**Comment by ozett** [comment]
i tried to fix with:
```
npm uninstall net-keepalive@0.3.8 (--> success)
npm install net-keepalive (--> success with recent ver 1.2.xx)
```
than again errors: 
```
binding.target.mk:101: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/node-hikvision-api/node_modules/net-keepalive/node_modules/ref/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.37-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/node-hikvision-api/node_modules/net-keepalive/node_modules/ref
gyp ERR! node -v v10.20.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN notsup Unsupported engine for net-keepalive@0.3.8: wanted: {"node":">=0.10 <=0.12||>=4 <=7"} (current: {"node":"10.20.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: net-keepalive@0.3.8
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: nyc@11.9.0 (node_modules/net-keepalive/node_modules/nyc):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Verification failed while extracting nyc@11.9.0:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Verification failed while extracting nyc@11.9.0:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha512-w8OdJAhXL5izerzZMdqzYKMj/pgHJyY3qEPYBjLLxrhcVoHEY9pU5ENIiZyCgG9OR7x3VcUMoD40o6PtVpfR4g== integrity checksum failed when using sha512: wanted sha512-w8OdJAhXL5izerzZMdqzYKMj/pgHJyY3qEPYBjLLxrhcVoHEY9pU5ENIiZyCgG9OR7x3VcUMoD40o6PtVpfR4g== but got sha512-7hnY/gIlk8G13ESGEsANoZY5c/hgUqmStkDwm+NCIMLNtPlY7Vw7uy1QHhrmFxejPbpajrAYvuNMMuHmkID7/Q==. (2734351 bytes)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ref@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ref@1.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-11T12_32_46_873Z-debug.log
pi@eg-buero-olaf:~/.node-red $
```
something outdated with the dependencies? 
how to overcome?

**Comment by teemuhirsikangas** [comment]
this is quite old project for me, it works for me with nodejs 8.x:

`git clone https://github.com/teemuhirsikangas/node-hikvision-omxplayer.git`

nodejs needs to be version 8 (does not work with 10 or newer, haven't had the time to update)
` sudo curl -sL https://deb.nodesource.com/setup_8.x | bash -`
`node -v`
v8.17.0

` cd node-hikvision-omxplayer/`
` npm install`
` sudo npm install -g pm2`
edit the config file:  `nano config.js`

start:
` pm2 start index.js`

if you want it to autostart on next reboot:
` pm2 save`

Added these also to the readme.md file

**Comment by ozett** [comment]
thanks for reply, i will see if i find a spare  sd-card for my raspberry to give your solution a try.
my impression was, that the dependencies from the hikvison-api for net-keepalive was fixed to the old version what causes the error. maybe i go  this new road with older version 8.
thanks a lot, even for an old project
